before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: DL9BwhkODYkeBijT/q0FaSfQ9LzHAmRSXSaQMRTWgfqk5roUI3TuQrv8EgQAPUFzucGdC0jDg8xpxK1cqntWzOJwI7JvfMZm1QA1zDcnY9mdYXKe1sOzZXYliKjWJYKbzvog1YDu1EaZBdpLoD3N06Z6qMErdB1Eeewv9fNgEkq0ha4S807WkeljuD1uA6SaDejnpMQJn8+Cv4+n8PGf+GAAxZbYwQkD3XWSwp/xzMbI+qjtgsNOSLQlXsVNQXNZGu5xgj4kEBoDT7CHUMtCOxZT6UTKlGco3OadILcaRsxMypTVwZY4TNFa4JIXhUq7B+KaAnIcxyNPPpHqGESjFRpw8dpPCRGeEBqvykz3NQqJrlD+ImJjolA21bKJtPpGAEWp23w1kXWWlzhMXjgP+tHcshRM4pEekfdVWcJn2smrmGBTh7NIJW714mFS+3v3BbgxGxVAyT5LMuk+ccLg8iiujieRJgj6yRw2ZgQEKGty9KTS/Nkzdui7P65UdWa13AVb3dOWAQfCC7IesAkDV1LM9dI0ayPwjxzua+qBvZ0Tlo0xI8MTA5HXmzE+rhs88jTCkvCSL7RtW9POccn02B411r3I42fJtmY0YSBfLs0yaE/JH1dN2pp5YGzzEWu7AQZoYEOtfpXUqVR76mziNuexDLjTOfHCpio4cThfd+4= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
